### ISSUE TITLE
Check for window available before setting up midi access

### ISSUE THREAD

**Issue by codenakama** [nickroberts404/react-midi-hooks#1]
I would like to start to say that this library is really good and very welcome. It helps me get stuff done with MIDI and React 16+ really fast.

However using it with nextjs a SSR framework for react I had issues with `window is not defined` errors. This could probably be easily fixed by a simple `if(typeof window !== 'undefined` check before doing anything.

Let me know your thoughts.

**Comment by codenakama** [comment]
TO add context I worked around this but just this would simplify my code.

**Comment by nickroberts404** [comment]
Hi @codenakama, thanks for the nice words, I'm really happy you like it!
536502c3d3397e927084d2c309289b7875cc4f05 should fix it up 👍
