### ISSUE TITLE
Don't initialize midi controls with 0

### ISSUE THREAD

**Issue by Ansimorph** [nickroberts404/react-midi-hooks#2]
Hi,

First of all, thanks for making midi-interactions with your awesome hooks! Thanks for putting in the effort.

I have an interface controlled by a midi controller. The interface has a lot of sensible default values for the different encoders. These are all set to zero by the useMIDIControl hook. So in order to return the interface to a workable state I need to wiggle all midi-knobs whenever the app is loaded. That's tiresome.

Is there a reason to initialize with 0 even though the value is unknown at that point? Wouldn't undefined better match the state?

**Comment by nickroberts404** [comment]
Hey @Ansimorph, sorry for the late reply, I've been away from open source but am beginning to work on this project again. Updated `useMIDIControl` to use `undefined` as default value. Just pushed `@1.0.2`, thanks for the suggestion!
