### ISSUE TITLE
Having trouble making this work...

### ISSUE THREAD

**Issue by rchrdnsh** [nickroberts404/react-midi-hooks#5]
Trying to set this up in a Gatsby app and having trouble, getting this error message in the console:

<img width="824" alt="Screen Shot 2020-06-08 at 1 21 34 PM" src="https://user-images.githubusercontent.com/7884263/84076855-59c74000-a98b-11ea-92ee-df432bcebfea.png">

not sure if this is what is stopping your hooks from working for me...trying to make it work in Chrome 83...

I am trying to use it in a Gatsby JS / Netlify Web App, with the following code in the layout component, first as it's own component, then inside the main layout component:

```jsx
const MIDINoteLog = ({ input }) => {
  const event = useMIDINote(input, { channel: 1 }) // Intially returns {}
  const { on, note, velocity, channel } = event
  return (
    <p>
      Note {note} {on ? 'on' : 'off'} ({velocity}) on channel {channel}
    </p>
  )
}
```

```jsx
const Layout = ({ children, location }) => {

  const [inputs, outputs] = useMIDI(); // Initially returns [[], []]
  console.log(inputs)

  return (
    <>
      // other stuff...
      <MIDIInfo/>
      // other stuff...
  )
}
```

...but when i play my midi keyboard, no midi info pops up in my `<MIDIInfo>` component.

When I go to other websites, like this one, in chrome:

https://www.onlinemusictools.com/kb/

...my MIDI keyboard works just fine.

So, I don't know what I should do or how I should approach this next...dunno if there is an issue with the library, or with my code, as I really don't understand it well enough yet.

Thank you for your time and help NIck!

**Comment by nickroberts404** [comment]
Hey @rchrdnsh, sorry for the late reply! It totally was a bug in the library, the result of a refactor without proper testing. Just pushed @1.0.2, should have the fix and will plan on adding tests next!

**Comment by rchrdnsh** [comment]
yay, success! I'm getting MIDI Messages into my app now, thank you!

Now, on to building cool stuff with this XD
